
export const  calenderLocaleFeilds = 
{
"de" : {
        firstDayOfWeek: 0,
        dayNames: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
        dayNamesShort: ['Son', 'Mon', 'Die', 'Mit', 'Don', 'Fre', 'Sam'],
        dayNamesMin: ['S', 'M', 'D', 'M ', 'D', 'F ', 'S'],
        monthNames: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
        monthNamesShort: ['Jan', 'Feb', 'MÃ¤r', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
        dateFormat: "dd.mm.yy",
        placeHolder: "DD.MM.YYYY",
        localeDateFormat: "dd.MM.yyyy",
        amLocaleDateFormat: "DD.MM.YYYY",
        dateAndTimeFormat: 'DD.MM.YYYY hh:mm:ss'
    },
      
"gb" : {
        firstDayOfWeek: 0,
        dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        dayNamesShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        dayNamesMin: ["Su","Mo","Tu","We","Th","Fr","Sa"],
        monthNames: [ "January","February","March","April","May","June","July","August","September","October","November","December" ],
        monthNamesShort: [ "Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul", "Aug", "Sep", "Oct", "Nov", "Dec" ],
        dateFormat: "dd/mm/yy",
        placeHolder: "DD/MM/YYYY",
        localeDateFormat: "dd/MM/yyyy",
        amLocaleDateFormat: "DD/MM/YYYY",
        dateAndTimeFormat: 'DD/MM/YYYY hh:mm:ss'
    },
"us" : {
        firstDayOfWeek: 0,
        dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        dayNamesMin: ["Su","Mo","Tu","We","Th","Fr","Sa"],
        dayNamesShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        monthNames: [ "January","February","March","April","May","June","July","August","September","October","November","December" ],
        monthNamesShort: [ "Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul", "Aug", "Sep", "Oct", "Nov", "Dec" ],
        dateFormat: "mm/dd/yy",
        placeHolder: "MM/DD/YYYY",
        localeDateFormat: "MM/dd/yyyy",
        amLocaleDateFormat: "MM/DD/YYYY",
        dateAndTimeFormat: 'MM/DD/YYYY hh:mm:ss'
    },    
"es-MX": {
        firstDayOfWeek: 0,
        dayNames: [ "domingo","lunes","martes","miércoles","jueves","viernes","sábado" ],
        dayNamesShort: [ "dom","lun","mar","mié","jue","vie","sáb" ],
        dayNamesMin: [ "D","L","M","X","J","V","S" ],
        monthNames: [ "enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre" ],
        monthNamesShort: [ "ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic" ],
        dateFormat: "dd/mm/yy",
        placeHolder: "DD/MM/YYYY",
        localeDateFormat: "dd/MM/yyyy",
        amLocaleDateFormat: "DD/MM/YYYY",
        dateAndTimeFormat: 'DD/MM/YYYY hh:mm:ss'
    },
"es": {
        firstDayOfWeek: 0,
        dayNames: [ "domingo","lunes","martes","miércoles","jueves","viernes","sábado" ],
        dayNamesShort: [ "dom","lun","mar","mié","jue","vie","sáb" ],
        dayNamesMin: [ "D","L","M","X","J","V","S" ],
        monthNames: [ "enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre" ],
        monthNamesShort: [ "ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic" ],
        dateFormat: "dd/mm/yy",
        placeHolder: "DD/MM/YYYY",
        localeDateFormat: "dd/MM/yyyy",
        amLocaleDateFormat: "DD/MM/YYYY",
        dateAndTimeFormat: 'DD/MM/YYYY hh:mm:ss'
    },
"fr": {
        firstDayOfWeek: 0,
        dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
        dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'], 
        dayNamesMin:  ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
        monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre' ],
        monthNamesShort: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc' ],
        dateFormat: "dd/mm/yy",
        placeHolder: "DD/MM/YYYY",
        localeDateFormat: "dd/MM/yyyy",
        amLocaleDateFormat: "DD/MM/YYYY",
        dateAndTimeFormat: 'DD/MM/YYYY hh:mm:ss'
    },
"he": {
        firstDayOfWeek: 0,
        dayNames: ['ראשון','שני','שלישי','רביעי','חמישי','שישי','שבת'],
        dayNamesShort: ['א\'','ב\'','ג\'','ד\'','ה\'','ו\'','שבת'],
        dayNamesMin: ['א\'','ב\'','ג\'','ד\'','ה\'','ו\'','שבת'],
        monthNames: ['ינואר','פברואר','מרץ','אפריל','מאי','יוני', 'יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'], 
        monthNamesShort: ['1','2','3','4','5','6', '7','8','9','10','11','12'],
        dateFormat: "dd.mm.yy",
        placeHolder: "DD.MM.YYYY",
        localeDateFormat: "dd.MM.yyyy",
        amLocaleDateFormat: "DD.MM.YYYY",
        dateAndTimeFormat: 'DD.MM.YYYY hh:mm:ss'
    },
"it": {
        firstDayOfWeek: 0,
        dayNames: ['Domenica', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato'],
        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
        dayNamesMin: ['D', 'L', 'M', 'M ', 'G', 'V ', 'S'],
        monthNames: ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre' ],
        monthNamesShort: ['Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu', 'Lug', 'Ago', 'Set', 'Ott', 'Nov', 'Dic' ],
        dateFormat: "dd/mm/yy",
        placeHolder: "DD/MM/YYYY",
        localeDateFormat: "dd/MM/yyyy",
        amLocaleDateFormat: "DD/MM/YYYY",
        dateAndTimeFormat: 'DD/MM/YYYY hh:mm:ss'
    },
"jp": {
        firstDayOfWeek: 0,
        dayNames: [ "日曜日","月曜","火曜日","水曜日","木曜日","金曜日","土曜日" ],
        dayNamesShort: [ "太陽","月","火","結婚した","サル","金","土" ],
        dayNamesMin: [ "D","L","M","X","J","V","S" ],
        monthNames: [ "1月","2月","行進","4月","5月","六月","7月","8月","9月","10月","11月","12月" ],
        monthNamesShort: [ "1月","2月","行進","4月","5月","六月","7月","8月","9月","10月","11月","12月" ],
        dateFormat: "yy/mm/dd",
        placeHolder: "YYYY/MM/DD",
        localeDateFormat: "yyyy/MM/dd",
        amLocaleDateFormat: "YYYY/MM/DD",
        dateAndTimeFormat: 'YYYY/MM/DD hh:mm:ss'
    },
"pt-br": {
        firstDayOfWeek: 0,
        dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
        dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'],
        dayNamesMin: ['D','S','T','Q','Q','S','S'],
        monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'], 
        monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun', 'Jul','Ago','Set','Out','Nov','Dez'], 
        dateFormat: "dd/mm/yy",
        placeHolder: "DD/MM/YYYY",
        localeDateFormat: "dd/MM/yyyy",
        amLocaleDateFormat: "DD/MM/YYYY",
        dateAndTimeFormat: 'DD/MM/YYYY hh:mm:ss'
    },
"ar-sa": {
        firstDayOfWeek: 0,
        dayNames: ['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','يوم الجمعة','يوم السبت'],
        dayNamesShort: ['سو','مو','تو','نحن','ث','الاب','سا'],
        dayNamesMin: ['شمس','الإثنين','الثلاثاء','تزوج','الخميس','الجمعة','جلسنا'],
        monthNames: ['كانون الثاني','شهر فبراير','مارس','أبريل','قد','يونيو','يوليو','أغسطس','سبتمبر','شهر اكتوبر','شهر نوفمبر','ديسمبر'],
        monthNamesShort: ['يناير','فبراير','مارس','أبريل','قد','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
        dateFormat: "dd/mm/yy",
        placeHolder: "DD/MM/YYYY",
        localeDateFormat: "dd/MM/yyyy",
        amLocaleDateFormat: "DD/MM/YYYY",
        dateAndTimeFormat: 'DD/MM/YYYY hh:mm:ss'
},
"sv-se": {
    firstDayOfWeek: 0,
    dayNames: ['söndag','måndag','tisdag','onsdag','torsdag','fredag','lördag'],
    dayNamesShort: ['Su','Mo','Tu','Vi','th','Fr','Sa'],
    dayNamesMin: ['Sol','Mon','tue','ons','Thu','Fri','lör'],
    monthNames: [ 'januari', 'februari', 'Mars', 'april', 'Maj', 'juni', 'juli', 'augusti', 'september', 'oktober', 'november', 'december'], 
    monthNamesShort: ['jan', 'februari', 'mar', 'april', 'Maj', 'juni', 'juli', 'augusti', 'september', 'oktober', 'november', 'december'], 
    dateFormat: "yy-mm-dd",
    placeHolder: "YYYY-MM-DD",
    localeDateFormat: "yyyy-MM-dd",
    amLocaleDateFormat: "YYYY-MM-DD",
    dateAndTimeFormat: 'YYYY-MM-DD hh:mm:ss'
}
};
